package Login;

import Cadastrar.TelaCadastrar;
import Entity.TelaConsultar;
import Entity.DAO;
import Entity.Usuario;
import Menu.TelaMenu;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import org.mindrot.jbcrypt.BCrypt;

public class TelaLogin extends javax.swing.JFrame {
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloLogin = new javax.swing.JLabel();
        NomeUsuario = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        SenhaUsuario = new javax.swing.JLabel();
        BtnEntrar = new javax.swing.JButton();
        senhaTextField = new javax.swing.JPasswordField();
        BtnVoltar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Login");
        setMinimumSize(new java.awt.Dimension(323, 420));
        getContentPane().setLayout(null);

        TituloLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        TituloLogin.setForeground(new java.awt.Color(255, 255, 255));
        TituloLogin.setText("Login");
        getContentPane().add(TituloLogin);
        TituloLogin.setBounds(110, 20, 100, 51);

        NomeUsuario.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        NomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        NomeUsuario.setText("NOME DE USUÁRIO");
        getContentPane().add(NomeUsuario);
        NomeUsuario.setBounds(40, 90, 100, 16);

        nomeTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextField);
        nomeTextField.setBounds(40, 120, 210, 30);

        SenhaUsuario.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        SenhaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        SenhaUsuario.setText("SENHA");
        getContentPane().add(SenhaUsuario);
        SenhaUsuario.setBounds(40, 170, 35, 16);

        BtnEntrar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        BtnEntrar.setText("Entrar");
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEntrar);
        BtnEntrar.setBounds(170, 320, 110, 40);

        senhaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaTextField);
        senhaTextField.setBounds(40, 200, 210, 30);

        BtnVoltar1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        BtnVoltar1.setText("Sair");
        BtnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVoltar1);
        BtnVoltar1.setBounds(40, 320, 110, 39);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/biblioteca2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-220, 0, 540, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
    String login = nomeTextField.getText(); 
    String senhaDigitada = new String(senhaTextField.getPassword());

    if (login.isEmpty() || senhaDigitada.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Certifique-se de que os campos não estão vazios");
        return;
    }

    try { 
        DAO dao = new DAO();
        Usuario usuario = dao.buscarUsuarioPorLogin(login);

        if (usuario != null) {
            String senhaNoBanco = usuario.getSenha();
            
            if (BCrypt.checkpw(senhaDigitada, senhaNoBanco)) {
                JOptionPane.showMessageDialog(null, "Bem-vindo, " + usuario.getLogin() + "!");
                TelaMenu telaMenu = new TelaMenu();
                telaMenu.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
        }
    } catch (Exception e) { 
        JOptionPane.showMessageDialog(null, "Problemas técnicos. Tente novamente mais tarde");
        e.printStackTrace();
    } 
    }//GEN-LAST:event_BtnEntrarActionPerformed

    private void senhaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaTextFieldActionPerformed

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void BtnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltar1ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_BtnVoltar1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
               /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JButton BtnVoltar1;
    private javax.swing.JLabel NomeUsuario;
    private javax.swing.JLabel SenhaUsuario;
    private javax.swing.JLabel TituloLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JPasswordField senhaTextField;
    // End of variables declaration//GEN-END:variables

    public JTextField getNome() {
        return nomeTextField;
    }

    public void setNome(JTextField Nome) {
        this.nomeTextField = Nome;
    }

    public JPasswordField getSenha() {
        return senhaTextField;
    }

    public void setSenha(JPasswordField Senha) {
        this.senhaTextField = Senha;
    }

}
